# State Machine Constants
STATE_IDLE = "IDLE"
STATE_READY = "READY"
STATE_RUNNING = "RUNNING"
STATE_STOPPING = "STOPPING"
STATE_STOPPED = "STOPPED"
STATE_ALARM = "ALARM"
STATE_ERROR = "ERROR"
STATE_CALIBRATING = "CALIBRATING"

# Quality Status Constants
STATUS_PASS = "ผ่าน"
STATUS_OUT_OF_RANGE = "ออกนอกเกณฑ์"
STATUS_NO_SILK = "ไม่พบเส้นไหม"

# Stop Reasons
REASON_TARGET_REACHED = "TARGET_REACHED"
REASON_NO_SILK = "NO_SILK"
REASON_OUT_OF_RANGE = "OUT_OF_RANGE"
REASON_CAMERA_ERROR = "CAMERA_ERROR"
REASON_EMERGENCY_STOP = "EMERGENCY_STOP"
REASON_MANUAL_STOP = "MANUAL_STOP"
